"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const auth_middleware_1 = require("../../middlewares/auth.middleware");
const permission_middleware_1 = require("../../middlewares/permission.middleware");
const sync_controller_1 = require("./sync.controller");
const router = (0, express_1.Router)();
router.use(auth_middleware_1.authMiddleware);
router.get('/status', (0, permission_middleware_1.requirePermission)('admin.view'), sync_controller_1.getSyncStatusController);
router.post('/retry', (0, permission_middleware_1.requirePermission)('admin.edit'), sync_controller_1.retryPendingSyncController);
exports.default = router;
